language: python
python:
  - "3.4"
#  - "3.5" -- Travis doesn't yet support 3.5 testing (Sept. 13, 2015)
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install coveralls
# command to run tests
script: nosetests
# run on container-based infrastructure
sudo: false

script:
  - python setup.py install
  - "coverage run --source=pywebhooks setup.py test"
after_success:
  - coveralls
